<?php
/**
 * ParcelTemplateFedExEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ParcelTemplateFedExEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Name | Dimensions| |:---|:---|:---| | FedEx_Box_10kg | FedEx® 10kg Box | 15.81 x 12.94 x 10.19 in| | FedEx_Box_25kg | FedEx® 25kg Box | 54.80 x 42.10 x 33.50 in| | FedEx_Box_Extra_Large_1 | FedEx® Extra Large Box (X1) | 11.88 x 11.00 x 10.75 in| | FedEx_Box_Extra_Large_2 | FedEx® Extra Large Box (X2) | 15.75 x 14.13 x 6.00 in| | FedEx_Box_Large_1 | FedEx® Large Box (L1) | 17.50 x 12.38 x 3.00 in| | FedEx_Box_Large_2 | FedEx® Large Box (L2) | 11.25 x 8.75 x 7.75 in| | FedEx_Box_Medium_1 | FedEx® Medium Box (M1) | 13.25 x 11.50 x 2.38 in| | FedEx_Box_Medium_2 | FedEx® Medium Box (M2) | 11.25 x 8.75 x 4.38 in| | FedEx_Box_Small_1 | FedEx® Small Box (S1) | 12.38 x 10.88 x 1.50 in| | FedEx_Box_Small_2 | FedEx® Small Box (S2) | 11.25 x 8.75 x 4.38 in| | FedEx_Envelope | FedEx® Envelope | 12.50 x 9.50 x 0.80 in| | FedEx_Padded_Pak | FedEx® Padded Pak | 11.75 x 14.75 x 2.00 in| | FedEx_Pak_1 | FedEx® Large Pak | 15.50 x 12.00 x 0.80 in| | FedEx_Pak_2 | FedEx® Small Pak | 12.75 x 10.25 x 0.80 in| | FedEx_Tube | FedEx® Tube | 38.00 x 6.00 x 6.00 in| | FedEx_XL_Pak | FedEx® Extra Large Pak | 17.50 x 20.75 x 2.00 in|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ParcelTemplateFedExEnum
{
    /**
     * Possible values of this enum
     */
    public const BOX_10KG = 'FedEx_Box_10kg';

    public const BOX_25KG = 'FedEx_Box_25kg';

    public const BOX_EXTRA_LARGE_1 = 'FedEx_Box_Extra_Large_1';

    public const BOX_EXTRA_LARGE_2 = 'FedEx_Box_Extra_Large_2';

    public const BOX_LARGE_1 = 'FedEx_Box_Large_1';

    public const BOX_LARGE_2 = 'FedEx_Box_Large_2';

    public const BOX_MEDIUM_1 = 'FedEx_Box_Medium_1';

    public const BOX_MEDIUM_2 = 'FedEx_Box_Medium_2';

    public const BOX_SMALL_1 = 'FedEx_Box_Small_1';

    public const BOX_SMALL_2 = 'FedEx_Box_Small_2';

    public const ENVELOPE = 'FedEx_Envelope';

    public const PADDED_PAK = 'FedEx_Padded_Pak';

    public const PAK_1 = 'FedEx_Pak_1';

    public const PAK_2 = 'FedEx_Pak_2';

    public const TUBE = 'FedEx_Tube';

    public const XL_PAK = 'FedEx_XL_Pak';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::BOX_10KG,
            self::BOX_25KG,
            self::BOX_EXTRA_LARGE_1,
            self::BOX_EXTRA_LARGE_2,
            self::BOX_LARGE_1,
            self::BOX_LARGE_2,
            self::BOX_MEDIUM_1,
            self::BOX_MEDIUM_2,
            self::BOX_SMALL_1,
            self::BOX_SMALL_2,
            self::ENVELOPE,
            self::PADDED_PAK,
            self::PAK_1,
            self::PAK_2,
            self::TUBE,
            self::XL_PAK
        ];
    }
}


