<?php
/**
 * ServiceLevelDHLGermanyEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelDHLGermanyEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | dhl_germany_europaket | DHL Germany Europaket| | dhl_germany_paket | DHL Germany Paket| | dhl_germany_paket_connect | DHL Germany Paket Connect| | dhl_germany_paket_international | DHL Germany Paket International| | dhl_germany_paket_priority | DHL Germany Paket Priority| | dhl_germany_paket_sameday | DHL Germany Paket Sameday|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelDHLGermanyEnum
{
    /**
     * Possible values of this enum
     */
    public const EUROPAKET = 'dhl_germany_europaket';

    public const PAKET = 'dhl_germany_paket';

    public const PAKET_CONNECT = 'dhl_germany_paket_connect';

    public const PAKET_INTERNATIONAL = 'dhl_germany_paket_international';

    public const PAKET_PRIORITY = 'dhl_germany_paket_priority';

    public const PAKET_SAMEDAY = 'dhl_germany_paket_sameday';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EUROPAKET,
            self::PAKET,
            self::PAKET_CONNECT,
            self::PAKET_INTERNATIONAL,
            self::PAKET_PRIORITY,
            self::PAKET_SAMEDAY
        ];
    }
}


