<?php
/**
 * ServiceLevelEvriUKEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelEvriUKEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | hermes_uk_courier_service | Courier Collection| | hermes_uk_parcelshop_dropoff | ParcelShop Drop-Off| | hermes_uk_parcelshop_dropoff_nextday | ParcelShop Drop-Off Next Day| | hermes_uk_postable | Postable| | hermes_uk_postable_nextday | Postable Next Day|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelEvriUKEnum
{
    /**
     * Possible values of this enum
     */
    public const COURIER_SERVICE = 'hermes_uk_courier_service';

    public const PARCELSHOP_DROPOFF = 'hermes_uk_parcelshop_dropoff';

    public const PARCELSHOP_DROPOFF_NEXTDAY = 'hermes_uk_parcelshop_dropoff_nextday';

    public const POSTABLE = 'hermes_uk_postable';

    public const POSTABLE_NEXTDAY = 'hermes_uk_postable_nextday';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::COURIER_SERVICE,
            self::PARCELSHOP_DROPOFF,
            self::PARCELSHOP_DROPOFF_NEXTDAY,
            self::POSTABLE,
            self::POSTABLE_NEXTDAY
        ];
    }
}


