<?php
/**
 * ServiceLevelPurolatorEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelPurolatorEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | purolator_ground | Ground| | purolator_ground9_am | Ground 9am| | purolator_ground1030_am | Ground 10:30am| | purolator_ground_distribution | Ground Distribution| | purolator_ground_evening | Ground Evening| | purolator_ground_us | Ground US| | purolator_express | Express| | purolator_express9_am | Express 9am| | purolator_express1030_am | Express 10am| | purolator_express_evening | Express Evening| | purolator_express_us | Express US| | purolator_express_us9_am | Express US 9am| | purolator_express_us1030_am | Express US 10:30am| | purolator_express_us1200 | Express US 12pm| | purolator_express_international | Express International| | purolator_express_international9_am | Express International 9am| | purolator_express_international1030_am | Express International 10:30am| | purolator_express_international1200 | Express International 12pm|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelPurolatorEnum
{
    /**
     * Possible values of this enum
     */
    public const GROUND = 'purolator_ground';

    public const GROUND9_AM = 'purolator_ground9_am';

    public const GROUND1030_AM = 'purolator_ground1030_am';

    public const GROUND_DISTRIBUTION = 'purolator_ground_distribution';

    public const GROUND_EVENING = 'purolator_ground_evening';

    public const GROUND_US = 'purolator_ground_us';

    public const EXPRESS = 'purolator_express';

    public const EXPRESS9_AM = 'purolator_express9_am';

    public const EXPRESS1030_AM = 'purolator_express1030_am';

    public const EXPRESS_EVENING = 'purolator_express_evening';

    public const EXPRESS_US = 'purolator_express_us';

    public const EXPRESS_US9_AM = 'purolator_express_us9_am';

    public const EXPRESS_US1030_AM = 'purolator_express_us1030_am';

    public const EXPRESS_US1200 = 'purolator_express_us1200';

    public const EXPRESS_INTERNATIONAL = 'purolator_express_international';

    public const EXPRESS_INTERNATIONAL9_AM = 'purolator_express_international9_am';

    public const EXPRESS_INTERNATIONAL1030_AM = 'purolator_express_international1030_am';

    public const EXPRESS_INTERNATIONAL1200 = 'purolator_express_international1200';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GROUND,
            self::GROUND9_AM,
            self::GROUND1030_AM,
            self::GROUND_DISTRIBUTION,
            self::GROUND_EVENING,
            self::GROUND_US,
            self::EXPRESS,
            self::EXPRESS9_AM,
            self::EXPRESS1030_AM,
            self::EXPRESS_EVENING,
            self::EXPRESS_US,
            self::EXPRESS_US9_AM,
            self::EXPRESS_US1030_AM,
            self::EXPRESS_US1200,
            self::EXPRESS_INTERNATIONAL,
            self::EXPRESS_INTERNATIONAL9_AM,
            self::EXPRESS_INTERNATIONAL1030_AM,
            self::EXPRESS_INTERNATIONAL1200
        ];
    }
}


