<?php
/**
 * ServiceLevelAsendiaEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelAsendiaEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | asendia_us_priority_tracked | Asendia USA Priority Tracked| | asendia_us_international_express | Asendia USA International Express| | asendia_us_international_priority_airmail | Asendia USA International Priority Airmail| | asendia_us_international_surface_airlift | Asendia USA International Surface Air Lift| | asendia_us_priority_mail_international | Asendia USA Priority Mail International| | asendia_us_priority_mail_express_international | Asendia USA Priority Mail Express International| | asendia_us_epacket | Asendia USA International ePacket| | asendia_us_other | Asendia USA Other Services (custom)|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelAsendiaEnum
{
    /**
     * Possible values of this enum
     */
    public const PRIORITY_TRACKED = 'asendia_us_priority_tracked';

    public const INTERNATIONAL_EXPRESS = 'asendia_us_international_express';

    public const INTERNATIONAL_PRIORITY_AIRMAIL = 'asendia_us_international_priority_airmail';

    public const INTERNATIONAL_SURFACE_AIRLIFT = 'asendia_us_international_surface_airlift';

    public const PRIORITY_MAIL_INTERNATIONAL = 'asendia_us_priority_mail_international';

    public const PRIORITY_MAIL_EXPRESS_INTERNATIONAL = 'asendia_us_priority_mail_express_international';

    public const EPACKET = 'asendia_us_epacket';

    public const OTHER = 'asendia_us_other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRIORITY_TRACKED,
            self::INTERNATIONAL_EXPRESS,
            self::INTERNATIONAL_PRIORITY_AIRMAIL,
            self::INTERNATIONAL_SURFACE_AIRLIFT,
            self::PRIORITY_MAIL_INTERNATIONAL,
            self::PRIORITY_MAIL_EXPRESS_INTERNATIONAL,
            self::EPACKET,
            self::OTHER
        ];
    }
}


