<?php
/**
 * ServiceLevelGlobegisticsEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelGlobegisticsEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | globegistics_priority_mail_express_international | Globegistics Priority Mail Express International| | globegistics_priority_mail_international | Globegistics Priority Mail International| | globegistics_priority_mail_express_international_pds | Globegistics Priority Mail Express International PreSort Drop Ship| | globegistics_priority_mail_international_pds | Globegistics Priority Mail International PreSort Drop Ship| | globegistics_epacket | Globegistics ePacket| | globegistics_ecom_tracked_ddp | Globegistics eCom Tracked DDP| | globegistics_ecom_packet_ddp | Globegistics eCom Packet DDP| | globegistics_ecom_priority_mail_international_ddp | Globegistics eCom Priority Mail International DDP| | globegistics_ecom_priority_mail_express_international_ddp | Globegistics eCom Priority Mail Express International DDP| | globegistics_ecom_extra | Globegistics eCom Extra| | globegistics_ecom_international_priority_airmail | Globegistics eCom International Priority Airmail| | globegistics_ecom_international_surface_airlift | Globegistics eCom International Surface Air Lift|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelGlobegisticsEnum
{
    /**
     * Possible values of this enum
     */
    public const PRIORITY_MAIL_EXPRESS_INTERNATIONAL = 'globegistics_priority_mail_express_international';

    public const PRIORITY_MAIL_INTERNATIONAL = 'globegistics_priority_mail_international';

    public const PRIORITY_MAIL_EXPRESS_INTERNATIONAL_PDS = 'globegistics_priority_mail_express_international_pds';

    public const PRIORITY_MAIL_INTERNATIONAL_PDS = 'globegistics_priority_mail_international_pds';

    public const EPACKET = 'globegistics_epacket';

    public const ECOM_TRACKED_DDP = 'globegistics_ecom_tracked_ddp';

    public const ECOM_PACKET_DDP = 'globegistics_ecom_packet_ddp';

    public const ECOM_PRIORITY_MAIL_INTERNATIONAL_DDP = 'globegistics_ecom_priority_mail_international_ddp';

    public const ECOM_PRIORITY_MAIL_EXPRESS_INTERNATIONAL_DDP = 'globegistics_ecom_priority_mail_express_international_ddp';

    public const ECOM_EXTRA = 'globegistics_ecom_extra';

    public const ECOM_INTERNATIONAL_PRIORITY_AIRMAIL = 'globegistics_ecom_international_priority_airmail';

    public const ECOM_INTERNATIONAL_SURFACE_AIRLIFT = 'globegistics_ecom_international_surface_airlift';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PRIORITY_MAIL_EXPRESS_INTERNATIONAL,
            self::PRIORITY_MAIL_INTERNATIONAL,
            self::PRIORITY_MAIL_EXPRESS_INTERNATIONAL_PDS,
            self::PRIORITY_MAIL_INTERNATIONAL_PDS,
            self::EPACKET,
            self::ECOM_TRACKED_DDP,
            self::ECOM_PACKET_DDP,
            self::ECOM_PRIORITY_MAIL_INTERNATIONAL_DDP,
            self::ECOM_PRIORITY_MAIL_EXPRESS_INTERNATIONAL_DDP,
            self::ECOM_EXTRA,
            self::ECOM_INTERNATIONAL_PRIORITY_AIRMAIL,
            self::ECOM_INTERNATIONAL_SURFACE_AIRLIFT
        ];
    }
}


