<?php
/**
 * ServiceLevelCouriersPleaseEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelCouriersPleaseEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | couriersplease_domestic_priority_auth_to_leave | Domestic Priority - Authority To Leave/POPPoints| | couriersplease_domestic_priority_sign_required | Domestic Priority - Signature Required| | couriersplease_gold_domestic_auth_to_leave | Gold Domestic - Authority To Leave/POPPoints| | couriersplease_gold_domestic_sign_required | Gold Domestic - Signature Required| | couriersplease_off_peak_auth_to_leave | Off Peak - Authority To Leave/POPPoints| | couriersplease_off_peak_sign_required | Off Peak - Signature Required| | couriersplease_parcel_auth_to_leave | Parcel - Authority To Leave| | couriersplease_parcel_sign_required | Parcel - Signature Required| | couriersplease_road_express | Road Express| | couriersplease_satchel_auth_to_leave | Satchel - Authority To Leave| | couriersplease_satchel_sign_required | Satchel - Signature Required|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelCouriersPleaseEnum
{
    /**
     * Possible values of this enum
     */
    public const DOMESTIC_PRIORITY_AUTH_TO_LEAVE = 'couriersplease_domestic_priority_auth_to_leave';

    public const DOMESTIC_PRIORITY_SIGN_REQUIRED = 'couriersplease_domestic_priority_sign_required';

    public const GOLD_DOMESTIC_AUTH_TO_LEAVE = 'couriersplease_gold_domestic_auth_to_leave';

    public const GOLD_DOMESTIC_SIGN_REQUIRED = 'couriersplease_gold_domestic_sign_required';

    public const OFF_PEAK_AUTH_TO_LEAVE = 'couriersplease_off_peak_auth_to_leave';

    public const OFF_PEAK_SIGN_REQUIRED = 'couriersplease_off_peak_sign_required';

    public const PARCEL_AUTH_TO_LEAVE = 'couriersplease_parcel_auth_to_leave';

    public const PARCEL_SIGN_REQUIRED = 'couriersplease_parcel_sign_required';

    public const ROAD_EXPRESS = 'couriersplease_road_express';

    public const SATCHEL_AUTH_TO_LEAVE = 'couriersplease_satchel_auth_to_leave';

    public const SATCHEL_SIGN_REQUIRED = 'couriersplease_satchel_sign_required';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOMESTIC_PRIORITY_AUTH_TO_LEAVE,
            self::DOMESTIC_PRIORITY_SIGN_REQUIRED,
            self::GOLD_DOMESTIC_AUTH_TO_LEAVE,
            self::GOLD_DOMESTIC_SIGN_REQUIRED,
            self::OFF_PEAK_AUTH_TO_LEAVE,
            self::OFF_PEAK_SIGN_REQUIRED,
            self::PARCEL_AUTH_TO_LEAVE,
            self::PARCEL_SIGN_REQUIRED,
            self::ROAD_EXPRESS,
            self::SATCHEL_AUTH_TO_LEAVE,
            self::SATCHEL_SIGN_REQUIRED
        ];
    }
}


