<?php
/**
 * ServiceLevelGLSUSEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelGLSUSEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | gls_us_cps | GSO Ground| | gls_us_eps | Early Priority Overnight| | gls_us_ess | Early Saturday Delivery| | gls_us_nps | Noon Priority Overnight| | gls_us_pds | Priority Overnight| | gls_us_sds | Saturday Delivery|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelGLSUSEnum
{
    /**
     * Possible values of this enum
     */
    public const CPS = 'gls_us_cps';

    public const EPS = 'gls_us_eps';

    public const ESS = 'gls_us_ess';

    public const NPS = 'gls_us_nps';

    public const PDS = 'gls_us_pds';

    public const SDS = 'gls_us_sds';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CPS,
            self::EPS,
            self::ESS,
            self::NPS,
            self::PDS,
            self::SDS
        ];
    }
}


