<?php
/**
 * ServiceLevelAramexAustraliaEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelAramexAustraliaEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | fastway_australia_parcel | Parcel| | fastway_australia_satchel | Satchel| | fastway_australia_box_small | Box Small| | fastway_australia_box_medium | Box Medium| | fastway_australia_box_large | Box Large|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelAramexAustraliaEnum
{
    /**
     * Possible values of this enum
     */
    public const PARCEL = 'fastway_australia_parcel';

    public const SATCHEL = 'fastway_australia_satchel';

    public const BOX_SMALL = 'fastway_australia_box_small';

    public const BOX_MEDIUM = 'fastway_australia_box_medium';

    public const BOX_LARGE = 'fastway_australia_box_large';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::PARCEL,
            self::SATCHEL,
            self::BOX_SMALL,
            self::BOX_MEDIUM,
            self::BOX_LARGE
        ];
    }
}


