<?php
/**
 * ServiceLevelCorreosEspanaEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelCorreosEspanaEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | correos_standard_home| Paquete Estándar| | correos_premium_home | Paquete Premium|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelCorreosEspanaEnum
{
    /**
     * Possible values of this enum
     */
    public const STANDARD_HOME = 'correos_standard_home';

    public const PREMIUM_HOME = 'correos_premium_home';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::STANDARD_HOME,
            self::PREMIUM_HOME
        ];
    }
}


