<?php
/**
 * ServiceLevelRoyalMailEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelRoyalMailEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | royal_mail_tracked_letter_boxable_24_no_signature | Royal Mail Tracked Letter-Boxable 24 No Signature| | royal_mail_tracked_letter_boxable_48_no_signature | Royal Mail Tracked Letter-Boxable 48 No Signature| | royal_mail_tracked_24_returns | Royal Mail Tracked Returns 24| | royal_mail_tracked_48_returns | Royal Mail Tracked Returns 48| | royal_mail_special_delivery_guaranteed_1pm | Special Delivery Guaranteed by 1pm | royal_mail_special_delivery_guaranteed_9am | Special Delivery Guaranteed by 9am | royal_mail_24 | RoyalMail 24 | royal_mail_48 | RoyalMail 48 | royal_mail_signed_for_first_class | Signed for First Class | royal_mail_signed_for_second_class | Signed for Second Class | royal_mail_standard_first_class | Standard First Class | royal_mail_standard_second_class | Standard Second Class | royal_mail_tracked_24_no_signature | Royal Mail Tracked 24 No Signature | royal_mail_tracked_48_no_signature | Royal Mail Ttacked 48 No Signature | royal_mail_intl_bus_mail_lrg_ltr_zone_sort_pri | International Business Mail Large Letter Zone Sort Priority | royal_mail_intl_bus_parcels_tracked_zone_sort | International Business Parcels Tracked Zone Sort | royal_mail_intl_bus_parcels_tracked_country_priced | International Business Parcels Tracked Country Priced | royal_mail_intl_bus_parcels_tracked_signed_zone_srt | International Business Parcels &amp; Signed Zone Sort | royal_mail_24_flat_rate | Royal Mail 24 Parcel Flat Rate | royal_mail_48_flat_rate | Royal Mail 48 Parcel Flat Rate
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelRoyalMailEnum
{
    /**
     * Possible values of this enum
     */
    public const TRACKED_LETTER_BOXABLE_24_NO_SIGNATURE = 'royal_mail_tracked_letter_boxable_24_no_signature';

    public const TRACKED_LETTER_BOXABLE_48_NO_SIGNATURE = 'royal_mail_tracked_letter_boxable_48_no_signature';

    public const TRACKED_24_RETURNS = 'royal_mail_tracked_24_returns';

    public const TRACKED_48_RETURNS = 'royal_mail_tracked_48_returns';

    public const SPECIAL_DELIVERY_GUARANTEED_1PM = 'royal_mail_special_delivery_guaranteed_1pm';

    public const SPECIAL_DELIVERY_GUARANTEED_9AM = 'royal_mail_special_delivery_guaranteed_9am';

    public const _24 = 'royal_mail_24';

    public const _48 = 'royal_mail_48';

    public const SIGNED_FOR_FIRST_CLASS = 'royal_mail_signed_for_first_class';

    public const SIGNED_FOR_SECOND_CLASS = 'royal_mail_signed_for_second_class';

    public const STANDARD_FIRST_CLASS = 'royal_mail_standard_first_class';

    public const STANDARD_SECOND_CLASS = 'royal_mail_standard_second_class';

    public const TRACKED_24_NO_SIGNATURE = 'royal_mail_tracked_24_no_signature';

    public const TRACKED_48_NO_SIGNATURE = 'royal_mail_tracked_48_no_signature';

    public const INTL_BUS_MAIL_LRG_LTR_ZONE_SORT_PRI = 'royal_mail_intl_bus_mail_lrg_ltr_zone_sort_pri';

    public const INTL_BUS_PARCELS_TRACKED_ZONE_SORT = 'royal_mail_intl_bus_parcels_tracked_zone_sort';

    public const INTL_BUS_PARCELS_TRACKED_COUNTRY_PRICED = 'royal_mail_intl_bus_parcels_tracked_country_priced';

    public const INTL_BUS_PARCELS_TRACKED_SIGNED_ZONE_SRT = 'royal_mail_intl_bus_parcels_tracked_signed_zone_srt';

    public const _24_FLAT_RATE = 'royal_mail_24_flat_rate';

    public const _48_FLAT_RATE = 'royal_mail_48_flat_rate';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::TRACKED_LETTER_BOXABLE_24_NO_SIGNATURE,
            self::TRACKED_LETTER_BOXABLE_48_NO_SIGNATURE,
            self::TRACKED_24_RETURNS,
            self::TRACKED_48_RETURNS,
            self::SPECIAL_DELIVERY_GUARANTEED_1PM,
            self::SPECIAL_DELIVERY_GUARANTEED_9AM,
            self::_24,
            self::_48,
            self::SIGNED_FOR_FIRST_CLASS,
            self::SIGNED_FOR_SECOND_CLASS,
            self::STANDARD_FIRST_CLASS,
            self::STANDARD_SECOND_CLASS,
            self::TRACKED_24_NO_SIGNATURE,
            self::TRACKED_48_NO_SIGNATURE,
            self::INTL_BUS_MAIL_LRG_LTR_ZONE_SORT_PRI,
            self::INTL_BUS_PARCELS_TRACKED_ZONE_SORT,
            self::INTL_BUS_PARCELS_TRACKED_COUNTRY_PRICED,
            self::INTL_BUS_PARCELS_TRACKED_SIGNED_ZONE_SRT,
            self::_24_FLAT_RATE,
            self::_48_FLAT_RATE
        ];
    }
}


