<?php
/**
 * ServiceLevelDHLeCommerceEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelDHLeCommerceEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | dhl_ecommerce_marketing_parcel_expedited | Marketing Parcel Expedited| | dhl_ecommerce_globalmail_business_ipa | GlobalMail Business IPA| | dhl_ecommerce_parcel_international_direct | Parcel International Direct| | dhl_ecommerce_parcels_expedited_max | Parcels Expedited Max| | dhl_ecommerce_bpm_ground | Bounded Printed Matter Ground| | dhl_ecommerce_priority_expedited | Priority Expedited| | dhl_ecommerce_globalmail_packet_ipa | GlobalMail Packet IPA| | dhl_ecommerce_globalmail_packet_isal | GlobalMail Packet ISAL| | dhl_ecommerce_easy_return_plus | Easy Return Plus| | dhl_ecommerce_marketing_parcel_ground | Marketing Parcel Ground| | dhl_ecommerce_first_class_parcel_expedited | First Class Parcel Expedited| | dhl_ecommerce_globalmail_business_priority | GlobalMail Business Priority| | dhl_ecommerce_parcels_expedited | Parcels Expedited| | dhl_ecommerce_globalmail_business_isal | GlobalMail Business ISAL| | dhl_ecommerce_parcel_plus_expedited_max | Parcel Plus Expedited Max| | dhl_ecommerce_globalmail_packet_plus | GlobalMail Packet Plus| | dhl_ecommerce_parcels_ground | Parcels Ground| | dhl_ecommerce_expedited | Expedited| | dhl_ecommerce_parcel_plus_ground | Parcel Plus Ground| | dhl_ecommerce_parcel_international_standard | Parcel International Standard| | dhl_ecommerce_bpm_expedited | Bounded Printed Matter Expedited| | dhl_ecommerce_parcel_international_expedited | Parcel International Expedited| | dhl_ecommerce_globalmail_packet_priority | GlobalMail Packet Priority| | dhl_ecommerce_easy_return_light | Easy Return Light| | dhl_ecommerce_parcel_plus_expedited | Parcel Plus Expedited| | dhl_ecommerce_globalmail_business_standard | GlobalMail Packet Standard| | dhl_ecommerce_ground | Ground| | dhl_ecommerce_globalmail_packet_standard | GlobalMail Business Standard|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelDHLeCommerceEnum
{
    /**
     * Possible values of this enum
     */
    public const MARKETING_PARCEL_EXPEDITED = 'dhl_ecommerce_marketing_parcel_expedited';

    public const GLOBALMAIL_BUSINESS_IPA = 'dhl_ecommerce_globalmail_business_ipa';

    public const PARCEL_INTERNATIONAL_DIRECT = 'dhl_ecommerce_parcel_international_direct';

    public const PARCELS_EXPEDITED_MAX = 'dhl_ecommerce_parcels_expedited_max';

    public const BPM_GROUND = 'dhl_ecommerce_bpm_ground';

    public const PRIORITY_EXPEDITED = 'dhl_ecommerce_priority_expedited';

    public const GLOBALMAIL_PACKET_IPA = 'dhl_ecommerce_globalmail_packet_ipa';

    public const GLOBALMAIL_PACKET_ISAL = 'dhl_ecommerce_globalmail_packet_isal';

    public const EASY_RETURN_PLUS = 'dhl_ecommerce_easy_return_plus';

    public const MARKETING_PARCEL_GROUND = 'dhl_ecommerce_marketing_parcel_ground';

    public const FIRST_CLASS_PARCEL_EXPEDITED = 'dhl_ecommerce_first_class_parcel_expedited';

    public const GLOBALMAIL_BUSINESS_PRIORITY = 'dhl_ecommerce_globalmail_business_priority';

    public const PARCELS_EXPEDITED = 'dhl_ecommerce_parcels_expedited';

    public const GLOBALMAIL_BUSINESS_ISAL = 'dhl_ecommerce_globalmail_business_isal';

    public const PARCEL_PLUS_EXPEDITED_MAX = 'dhl_ecommerce_parcel_plus_expedited_max';

    public const GLOBALMAIL_PACKET_PLUS = 'dhl_ecommerce_globalmail_packet_plus';

    public const PARCELS_GROUND = 'dhl_ecommerce_parcels_ground';

    public const EXPEDITED = 'dhl_ecommerce_expedited';

    public const PARCEL_PLUS_GROUND = 'dhl_ecommerce_parcel_plus_ground';

    public const PARCEL_INTERNATIONAL_STANDARD = 'dhl_ecommerce_parcel_international_standard';

    public const BPM_EXPEDITED = 'dhl_ecommerce_bpm_expedited';

    public const PARCEL_INTERNATIONAL_EXPEDITED = 'dhl_ecommerce_parcel_international_expedited';

    public const GLOBALMAIL_PACKET_PRIORITY = 'dhl_ecommerce_globalmail_packet_priority';

    public const EASY_RETURN_LIGHT = 'dhl_ecommerce_easy_return_light';

    public const PARCEL_PLUS_EXPEDITED = 'dhl_ecommerce_parcel_plus_expedited';

    public const GLOBALMAIL_BUSINESS_STANDARD = 'dhl_ecommerce_globalmail_business_standard';

    public const GROUND = 'dhl_ecommerce_ground';

    public const GLOBALMAIL_PACKET_STANDARD = 'dhl_ecommerce_globalmail_packet_standard';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MARKETING_PARCEL_EXPEDITED,
            self::GLOBALMAIL_BUSINESS_IPA,
            self::PARCEL_INTERNATIONAL_DIRECT,
            self::PARCELS_EXPEDITED_MAX,
            self::BPM_GROUND,
            self::PRIORITY_EXPEDITED,
            self::GLOBALMAIL_PACKET_IPA,
            self::GLOBALMAIL_PACKET_ISAL,
            self::EASY_RETURN_PLUS,
            self::MARKETING_PARCEL_GROUND,
            self::FIRST_CLASS_PARCEL_EXPEDITED,
            self::GLOBALMAIL_BUSINESS_PRIORITY,
            self::PARCELS_EXPEDITED,
            self::GLOBALMAIL_BUSINESS_ISAL,
            self::PARCEL_PLUS_EXPEDITED_MAX,
            self::GLOBALMAIL_PACKET_PLUS,
            self::PARCELS_GROUND,
            self::EXPEDITED,
            self::PARCEL_PLUS_GROUND,
            self::PARCEL_INTERNATIONAL_STANDARD,
            self::BPM_EXPEDITED,
            self::PARCEL_INTERNATIONAL_EXPEDITED,
            self::GLOBALMAIL_PACKET_PRIORITY,
            self::EASY_RETURN_LIGHT,
            self::PARCEL_PLUS_EXPEDITED,
            self::GLOBALMAIL_BUSINESS_STANDARD,
            self::GROUND,
            self::GLOBALMAIL_PACKET_STANDARD
        ];
    }
}


