<?php
/**
 * ServiceLevelAPCPostalEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelAPCPostalEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | apc_postal_parcelconnect_expedited | parcelConnect Expedited| | apc_postal_parcelconnect_priority | parcelConnect Priority| | apc_postal_parcelconnect_priority_delcon | parcelConnect Priority Delcon| | apc_postal_parcelconnect_priority_pqw | parcelConnect Priority PQW| | apc_postal_parcelconnect_book_service | parcelConnect Book Service| | apc_postal_parcelconnect_standard | parcelConnect Standard| | apc_postal_parcelconnect_epmi | parcelConnect ePMI| | apc_postal_parcelconnect_epacket | parcelConnect ePacket| | apc_postal_parcelconnect_epmei | parcelConnect ePMEI|
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelAPCPostalEnum
{
    /**
     * Possible values of this enum
     */
    public const EXPEDITED = 'apc_postal_parcelconnect_expedited';

    public const PRIORITY = 'apc_postal_parcelconnect_priority';

    public const PRIORITY_DELCON = 'apc_postal_parcelconnect_priority_delcon';

    public const PRIORITY_PQW = 'apc_postal_parcelconnect_priority_pqw';

    public const BOOK_SERVICE = 'apc_postal_parcelconnect_book_service';

    public const STANDARD = 'apc_postal_parcelconnect_standard';

    public const EPMI = 'apc_postal_parcelconnect_epmi';

    public const EPACKET = 'apc_postal_parcelconnect_epacket';

    public const EPMEI = 'apc_postal_parcelconnect_epmei';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EXPEDITED,
            self::PRIORITY,
            self::PRIORITY_DELCON,
            self::PRIORITY_PQW,
            self::BOOK_SERVICE,
            self::STANDARD,
            self::EPMI,
            self::EPACKET,
            self::EPMEI
        ];
    }
}


