<?php
/**
 * ServiceLevelFedExEnum
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceLevelFedExEnum Class Doc Comment
 *
 * @category Class
 * @description |Token | Service name| |:---|:---| | fedex_ground | FedEx Ground®| | fedex_home_delivery | FedEx Home Delivery®| | fedex_ground_economy | FedEx Ground® Economy| | fedex_2_day | FedEx 2Day®| | fedex_2_day_am | FedEx 2Day® A.M.| | fedex_express_saver | FedEx Express Saver®| | fedex_standard_overnight | FedEx Standard Overnight®| | fedex_priority_overnight | FedEx Priority Overnight®| | fedex_first_overnight | FedEx First Overnight®| | fedex_international_economy | FedEx International Economy®| | fedex_international_priority | FedEx International Priority®| | fedex_international_first | FedEx International First®| | fedex_europe_first_international_priority | FedEx International First®| | fedex_international_connect_plus | FedEx International Connect Plus| | fedex_first | FedEx First | | fedex_priority | FedEx Priority | | fedex_priority_express | FedEx Priority Express| | fedex_economy_select | FedEx® Economy | | fedex_regional_economy | FedEx® Regional Economy | | fedex_first_overnight_extra_hours | First Overnight® EH | | fedex_international_priority_express | International Priority® Express | | fedex_next_day_mid_morning | Next Day Mid Morning | | fedex_priority_overnight_extra_hours | Priority Overnight® EH | | fedex_standard_overnight_extra_hours | Standard Overnight® EH |
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ServiceLevelFedExEnum
{
    /**
     * Possible values of this enum
     */
    public const GROUND = 'fedex_ground';

    public const HOME_DELIVERY = 'fedex_home_delivery';

    public const SMART_POST = 'fedex_smart_post';

    public const GROUND_ECONOMY = 'fedex_ground_economy';

    public const _2_DAY = 'fedex_2_day';

    public const _2_DAY_AM = 'fedex_2_day_am';

    public const EXPRESS_SAVER = 'fedex_express_saver';

    public const STANDARD_OVERNIGHT = 'fedex_standard_overnight';

    public const PRIORITY_OVERNIGHT = 'fedex_priority_overnight';

    public const FIRST_OVERNIGHT = 'fedex_first_overnight';

    public const INTERNATIONAL_ECONOMY = 'fedex_international_economy';

    public const INTERNATIONAL_PRIORITY = 'fedex_international_priority';

    public const INTERNATIONAL_FIRST = 'fedex_international_first';

    public const EUROPE_FIRST_INTERNATIONAL_PRIORITY = 'fedex_europe_first_international_priority';

    public const INTERNATIONAL_CONNECT_PLUS = 'fedex_international_connect_plus';

    public const FIRST = 'fedex_first';

    public const PRIORITY = 'fedex_priority';

    public const PRIORITY_EXPRESS = 'fedex_priority_express';

    public const ECONOMY_SELECT = 'fedex_economy_select';

    public const REGIONAL_ECONOMY = 'fedex_regional_economy';

    public const FIRST_OVERNIGHT_EXTRA_HOURS = 'fedex_first_overnight_extra_hours';

    public const INTERNATIONAL_PRIORITY_EXPRESS = 'fedex_international_priority_express';

    public const NEXT_DAY_MID_MORNING = 'fedex_next_day_mid_morning';

    public const PRIORITY_OVERNIGHT_EXTRA_HOURS = 'fedex_priority_overnight_extra_hours';

    public const STANDARD_OVERNIGHT_EXTRA_HOURS = 'fedex_standard_overnight_extra_hours';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::GROUND,
            self::HOME_DELIVERY,
            self::SMART_POST,
            self::GROUND_ECONOMY,
            self::_2_DAY,
            self::_2_DAY_AM,
            self::EXPRESS_SAVER,
            self::STANDARD_OVERNIGHT,
            self::PRIORITY_OVERNIGHT,
            self::FIRST_OVERNIGHT,
            self::INTERNATIONAL_ECONOMY,
            self::INTERNATIONAL_PRIORITY,
            self::INTERNATIONAL_FIRST,
            self::EUROPE_FIRST_INTERNATIONAL_PRIORITY,
            self::INTERNATIONAL_CONNECT_PLUS,
            self::FIRST,
            self::PRIORITY,
            self::PRIORITY_EXPRESS,
            self::ECONOMY_SELECT,
            self::REGIONAL_ECONOMY,
            self::FIRST_OVERNIGHT_EXTRA_HOURS,
            self::INTERNATIONAL_PRIORITY_EXPRESS,
            self::NEXT_DAY_MID_MORNING,
            self::PRIORITY_OVERNIGHT_EXTRA_HOURS,
            self::STANDARD_OVERNIGHT_EXTRA_HOURS
        ];
    }
}


