<?php
/**
 * ParcelTemplateCouriersPleaseEnumTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ParcelTemplateCouriersPleaseEnumTest Class Doc Comment
 *
 * @category    Class
 * @description |Token | Name | Dimensions| |:---|:---|:---| | couriersplease_500g_satchel | 500g Satchel | 22.00 x 33.50 x 0.10 cm| | couriersplease_1kg_satchel | 1kg Satchel | 28.00 x 35.00 x 0.10 cm| | couriersplease_3kg_satchel | 3kg Satchel | 34.00 x 42.00 x 0.10 cm| | couriersplease_5kg_satchel | 5kg Satchel | 43.70 x 59.70 x 0.10 cm|
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelTemplateCouriersPleaseEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ParcelTemplateCouriersPleaseEnum"
     */
    public function testParcelTemplateCouriersPleaseEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
