<?php
/**
 * ServiceLevelCouriersPleaseEnumTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Shippo external API.
 *
 * Use this API to integrate with the Shippo service
 *
 * The version of the OpenAPI document: 2018-02-08
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ServiceLevelCouriersPleaseEnumTest Class Doc Comment
 *
 * @category    Class
 * @description |Token | Service name| |:---|:---| | couriersplease_domestic_priority_auth_to_leave | Domestic Priority - Authority To Leave/POPPoints| | couriersplease_domestic_priority_sign_required | Domestic Priority - Signature Required| | couriersplease_gold_domestic_auth_to_leave | Gold Domestic - Authority To Leave/POPPoints| | couriersplease_gold_domestic_sign_required | Gold Domestic - Signature Required| | couriersplease_off_peak_auth_to_leave | Off Peak - Authority To Leave/POPPoints| | couriersplease_off_peak_sign_required | Off Peak - Signature Required| | couriersplease_parcel_auth_to_leave | Parcel - Authority To Leave| | couriersplease_parcel_sign_required | Parcel - Signature Required| | couriersplease_road_express | Road Express| | couriersplease_satchel_auth_to_leave | Satchel - Authority To Leave| | couriersplease_satchel_sign_required | Satchel - Signature Required|
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ServiceLevelCouriersPleaseEnumTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ServiceLevelCouriersPleaseEnum"
     */
    public function testServiceLevelCouriersPleaseEnum()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
